### ISSUE TITLE
Project TODO List

### ISSUE THREAD

**Issue by edward62740** [edward62740/ot-IPR#1]
Project-level TODO list.

RADAR Sensor
- [x] Complete custom PCB (EFR32MG24 + A111)
- [x] Testing and validation of PCB
- [x] Initial testing of IPv6 network and direct connections with database
- [x] Initial testing of A111 SDK and drivers
- [x] Use DMA for SPI transfers
- [x] Development of low-power code (deployment)
- [x] Enclosure

Thread BR
- [x] Testing of NCP mode on CC2652RB dev board
- [x] Testing of OTBR on supported board
- [x] Linking of NCP and OTBR over USB (deployment?)
- [x] Global IPv6 routing from Thread network
- [x] Find more reliable connections to interface the two systems

Misc
- [x] #3 
- [x] CoAP server -> devices
- [x] Align to OPSEC. Dispose of used temp keys and passwords in deployment
- [x] System-level reliability and stress tests
- [x] Visualization of sensor data and status on Grafana
